### ISSUE TITLE
Mirroring Docker container on Quay.io?

### ISSUE THREAD

**Issue by rpetit3** [ncbi/sra-human-scrubber#7]
Hello! 

We've been running into some Docker pull limits. Would it be possible to create a mirror on Quay.io?

Thank you very much!

**Comment by multikengineer** [comment]
Apologies for the tardy reply. 

>We've been running into some Docker pull limits.

Are you pulling with authenticated requests?
 https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests
 As I understand:
`After you've authenticated to the account, you won't be pulling the image as an anonymous user but as an authenticated user. The image download will count against your personal limit of 200 downloads per six hours instead of the 100 downloads shared across all anonymous cluster users.`
Would that get you past your problems?

>Would it be possible to create a mirror on Quay.io?

At the moment anyway I not at liberty to mirror on Quay.io.

**Comment by rpetit3** [comment]
Thank you for the response! I'm not pulling with an authenticated request, due to it not always being available.

I think it would be definitely worth looking into [Docker's Open Source Project](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/), which would remove the pull limit for users using NCBI images. 

I think you've answered my question so I will close this. Thanks again!

**Comment by multikengineer** [comment]
Robert - you beat me to the punch!  I just earlier today requested that those in the position to do so enquire: I looked at the qualifications and I am pretty sure we will meet them. Thanks, and apologies again.
